# Generated by Django 3.0.8 on 2020-07-31 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('spares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparesAnalogCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Запчасти Аналог',
                'verbose_name_plural': 'Запчасти Аналог',
            },
        ),
        migrations.CreateModel(
            name='SparesOriginalCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Запчасти Оригинал',
                'verbose_name_plural': 'Запчасти Оригинал',
            },
        ),
        migrations.CreateModel(
            name='TypeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Типы работ',
                'verbose_name_plural': 'Типы работ',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('work_ratio', models.FloatField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('analog', models.ManyToManyField(through='work.SparesAnalogCount', to='spares.SparesAnalog')),
                ('cars', models.ManyToManyField(blank=True, to='car.Car')),
                ('original', models.ManyToManyField(through='work.SparesOriginalCount', to='spares.Spares')),
                ('type_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.TypeWork')),
            ],
            options={
                'verbose_name': 'Виды работ',
                'verbose_name_plural': 'Виды работ',
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='typework',
            index=models.Index(fields=['id', 'name'], name='work_typewo_id_d57322_idx'),
        ),
        migrations.AddField(
            model_name='sparesoriginalcount',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spares.Spares'),
        ),
        migrations.AddField(
            model_name='sparesoriginalcount',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Work'),
        ),
        migrations.AddField(
            model_name='sparesanalogcount',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spares.SparesAnalog'),
        ),
        migrations.AddField(
            model_name='sparesanalogcount',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Work'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['id', 'name'], name='work_work_id_238d02_idx'),
        ),
        migrations.AddIndex(
            model_name='sparesoriginalcount',
            index=models.Index(fields=['id', 'name', 'work'], name='work_spares_id_fce2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='sparesanalogcount',
            index=models.Index(fields=['id', 'name', 'work'], name='work_spares_id_e1ed84_idx'),
        ),
    ]
