# Generated by Django 3.0.8 on 2020-07-31 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200, unique=True)),
                ('cost', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Запчасти Оригинал',
                'verbose_name_plural': 'Запчасти Оригинал',
                'ordering': ['name__name'],
            },
        ),
        migrations.CreateModel(
            name='SparesAnalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200, unique=True)),
                ('cost', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Запчасти Аналог',
                'verbose_name_plural': 'Запчасти Аналог',
                'ordering': ['name__name'],
            },
        ),
        migrations.CreateModel(
            name='SparesName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Наименование',
                'verbose_name_plural': 'Наименование',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='sparesname',
            index=models.Index(fields=['id', 'name'], name='spares_spar_id_d45adc_idx'),
        ),
        migrations.AddField(
            model_name='sparesanalog',
            name='model',
            field=models.ManyToManyField(blank=True, to='car.Car'),
        ),
        migrations.AddField(
            model_name='sparesanalog',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spares.SparesName'),
        ),
        migrations.AddField(
            model_name='spares',
            name='model',
            field=models.ManyToManyField(blank=True, to='car.Car'),
        ),
        migrations.AddField(
            model_name='spares',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spares.SparesName'),
        ),
        migrations.AddIndex(
            model_name='sparesanalog',
            index=models.Index(fields=['id', 'name', 'part_number'], name='spares_spar_id_ae27ab_idx'),
        ),
        migrations.AddIndex(
            model_name='spares',
            index=models.Index(fields=['id', 'name', 'part_number'], name='spares_spar_id_3ccb58_idx'),
        ),
    ]
