# Generated by Django 3.0.8 on 2020-07-31 11:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], default='Diesel', max_length=16)),
                ('etype', models.CharField(blank=True, max_length=15)),
                ('capacity', models.FloatField(default=0.0)),
                ('start_year', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2020)])),
                ('end_year', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2020)])),
                ('now', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.BrandModel')),
            ],
            options={
                'ordering': ['model__name'],
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['id', 'model'], name='car_car_id_9ac6bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('model', 'fuel', 'capacity', 'start_year', 'end_year', 'etype', 'now')},
        ),
    ]
